site_name: Victor-个人文档库
repo_url: https://github.com/victor24680/victorDocs
copyright: Victor-个人文档库
site_url: http://docs.mylw.ink/

theme:
  name: material
  palette:
    primary: 'Blue Grey'
    accent: 'Pink'
  feature:
    tabs: false
  font:
    text: 'Ubuntu'
    code: 'Ubuntu Mono'
  language: 'zh'
nav:
  - 首页: index.md
  - Java知识库:
      - 坐标: Java知识库/maven工程坐标使用.md
      - Mybatis使用手册: Java知识库/Mybatis使用手册.md