site_name: Victor-个人文档库
repo_url: https://github.com/victor24680/victorDocs
copyright: Victor-个人文档库
site_url: http://docs.mylw.ink/
theme: readthedocs
nav:
  - Home: index.md
  - Java知识库: Java知识库